const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const F=require('./fixtures');
let clock=F.NOW;
class FixedDate extends Date { constructor(...args){super(...(args.length?args:[clock]));} static now(){return clock;} }
const html=fs.readFileSync('public/index.html','utf8');
// Parse the inline script, retaining real functions and replacing only initial load.
const source=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function computeLevels'));
new vm.Script(source);
const nodes=new Map();
function node(id){if(!nodes.has(id))nodes.set(id,{value:({globalSymbolInput:'SPY',globalMetricSelect:'gex',globalRangeSelect:'1.5',globalStrikesSelect:'21',hiroInterval:'5m',hiroRange:'1d'})[id]||'',innerText:'',innerHTML:'',style:{},classList:{add(){},remove(){},contains(){return true;}},addEventListener(){},focus(){},querySelector(){return node('close');}});return nodes.get(id);}
const storage=new Map();
const sandbox={Date:FixedDate,Intl,URLSearchParams,location:{search:''},document:{getElementById:node,addEventListener(){}},window:{},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setInterval(){},console:{warn(){}},fetch:async()=>{throw Error('Unexpected network');},Plotly:{newPlot(){}}};
vm.createContext(sandbox);vm.runInContext(source.replace(/\n        loadOptionsData\(\);/,'\n'),sandbox);
const run=s=>vm.runInContext(s,sandbox);
function server(fetch){const ctx={fetch,Date:FixedDate,Intl,process:{env:{CV_API_KEY:'fixture'}},console:{warn(){}},AbortController,AbortSignal,setTimeout,clearTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync('api/data.js','utf8').replace('export default async function','async function'),ctx);return ctx;}
const srv=server(sandbox.fetch);
const records=srv.processChainData(F.chain());sandbox.records=records;
let count=0;
async function test(name,fn){await fn();console.log('PASS '+name);count++;}
async function request(ctx,symbol='SPY'){const res={setHeader(){},status(n){this.code=n;return this;},json(body){this.body=body;return this;}};await ctx.handler({method:'GET',query:{symbol}},res);return res;}
const response=(status,data)=>({status,ok:status===200,json:async()=>data,text:async()=>JSON.stringify(data)});
(async()=>{
await test('scenario root matches analytic Black-Scholes equality',()=>{const a=F.analytic();const roots=sandbox.scenarioRoots(a.contracts,100,F.NOW);assert.equal(roots.length,1);assert.ok(Math.abs(roots[0]-a.root)<1e-7);assert.equal(sandbox.scenarioGamma(F.contract('call',{expiration:'2020-01-01'}),100,F.NOW),0);assert.equal(sandbox.scenarioRoots([F.contract('call')],100,F.NOW).length,0);});
await test('expected move requires both legs; dead straddle skips',()=>{assert.equal(sandbox.expectedMove([{expiration:F.EXP,strike:100,call_mid:3,put_mid:null}],100),null);assert.equal(sandbox.expectedMove([{expiration:F.EXP,strike:100,call_mid:3,put_mid:4}],100).em,7);});
await test('walls use separate gamma maxima, missing walls format --',()=>{const r=[{expiration:'x',strike:90,call_gex:5,put_gex:-100},{expiration:'x',strike:110,call_gex:10,put_gex:-2}];const lv=sandbox.computeLevels(r,100,['x'],true);assert.equal(lv.callWall,110);assert.equal(lv.putWall,90);const bad=sandbox.computeLevels([{expiration:'x',strike:100,call_gex:-3,put_gex:4}],100,['x']);assert.equal(sandbox.fmtStrike(bad.callWall),'--');assert.equal(sandbox.fmtStrike(bad.putWall),'--');});
await test('P/C undefined vs zero',()=>{assert.equal(sandbox.ratioText(sandbox.computeLevels([],100,[]).pcRatio),'n/a');assert.equal(sandbox.ratioText(sandbox.computeLevels([{expiration:'x',call_oi:3,put_oi:0,strike:100}],100,['x']).pcRatio),'0.00');});
await test('null Greeks preserved/excluded; coverage and spot-squared convention',()=>{assert.equal(records[0].contracts[1].gamma,null);const lv=sandbox.computeLevels(records,100,[F.EXP]);assert.equal(lv.netGex,20000);assert.equal(lv.netDex,500000);assert.equal(lv.gammaCoverage,.5);assert.equal(lv.deltaCoverage,.5);});
await test('IV numerator/denominator consistency, no silent ceiling',()=>{assert.equal(records[0].iv_num,20);assert.equal(records[0].iv_den,100);assert.equal(sandbox.computeLevels(records,100,[F.EXP]).atmIv,.2);const data=F.chain();data.chain[0].strikes[0][1][3]=6;assert.equal(srv.processChainData(data)[0].iv,6);});
await test('nearest strikes before display sort',()=>assert.deepEqual(Array.from(sandbox.nearestStrikes([90,91,92,99,100,101,110],100,3)),[99,100,101]));
await test('labels retain metric correspondence in both modes; DEX scope',()=>{run('currentData=records;chainMeta={spot:100};expirationsList=records.map(r=>r.expiration);');for(const mode of ['gex','dex']){node('globalMetricSelect').value=mode;sandbox.renderKPIs();assert.match(node('kpiNetGexLabel').innerText,/GEX/);assert.match(node('netGexVal').innerText,/20.0K/);assert.match(node('kpiNetDexLabel').innerText,/DEX/);assert.match(node('netDexVal').innerText,/500.0K/);}assert.equal(sandbox.computeLevels([...records,{...records[0],expiration:'other'}],100,[F.EXP],true).netDex,500000);});
await test('today-only and seven-calendar-day WEEK scopes',()=>{assert.equal(sandbox.swingExpirations(['2026-09-30'],'today',new Date(F.NOW)).length,0);assert.deepEqual(Array.from(sandbox.swingExpirations(['2026-09-29','2026-10-05','2026-10-06'],'week',new Date(F.NOW))),['2026-09-29','2026-10-05']);});
await test('429 short-circuits across symbols and force until cooldown expires',async()=>{let calls=0;sandbox.fetch=async()=>{calls++;return response(429,{error:'budget'});};await assert.rejects(sandbox.fetchChain('A'));await assert.rejects(sandbox.fetchChain('B',true));assert.equal(calls,1);clock+=3600001;sandbox.fetch=async()=>{calls++;return response(200,{records:[{}]});};await sandbox.fetchChain('B');assert.equal(calls,2);clock=F.NOW;run('budgetExhaustedUntil=0');});
await test('server 429 maps to 429; errors never cached',async()=>{let calls=0;const ctx=server(async url=>{if(url.includes('yahoo'))return response(500,{});calls++;return response(429,{});});assert.equal((await request(ctx)).code,429);assert.equal((await request(ctx)).code,429);assert.equal(calls,2);});
await test('server concurrent misses dedup; successful cache reused',async()=>{let calls=0,release;const gate=new Promise(r=>release=r);const ctx=server(async url=>{if(url.includes('yahoo'))return response(500,{});calls++;await gate;return response(200,F.chain());});const a=request(ctx),b=request(ctx);release();const out=await Promise.all([a,b]);assert.equal(calls,1);assert.equal(out[0].code,200);assert.equal(out[1].code,200);await request(ctx);assert.equal(calls,1);});
await test('server generic failure not cached',async()=>{let calls=0;const ctx=server(async url=>{if(url.includes('yahoo'))return response(500,{});calls++;return response(503,{});});assert.equal((await request(ctx)).code,503);assert.equal((await request(ctx)).code,503);assert.equal(calls,2);});
await test('demo expirations unique; timestamp DTE uses close',()=>{const demo=srv.generateDemoData('SPY');assert.equal(new Set(demo.map(r=>r.expiration)).size,8);assert.equal(new Set(demo.map(r=>r.expiration+'|'+r.strike)).size,demo.length);assert.equal(srv.expirationTimestamp('2026-09-29'),Date.parse('2026-09-29T20:00:00Z'));assert.equal(srv.expirationTimestamp('2026-12-01'),Date.parse('2026-12-01T21:00:00Z'));});
await test('all scenario roots reported for two sign changes',()=>{const exp=new Date(F.NOW+7*86400000).toISOString();const cs=[F.contract('call',{strike:90,expiration:exp}),F.contract('put',{strike:100,expiration:exp,oi:150}),F.contract('call',{strike:110,expiration:exp})];const roots=sandbox.scenarioRoots(cs,100,F.NOW);assert.equal(roots.length,2);assert.ok(roots[0]<100 && roots[1]>100);});
await test('zero OI contributes zero, missing IV does not dilute average',()=>{const chain=F.chain();chain.chain[0].strikes[0][1][11]=0;const r=srv.processChainData(chain)[0];assert.equal(r.dollar_gex,0);assert.equal(r.dollar_dex,0);assert.equal(r.iv_den,0);});
await test('baseline keeps prior day, reports added/removed/reversed strikes',()=>{const key='gexmap_dod_v2_live_SPY';storage.set(key,JSON.stringify({current:{date:'2026-09-28',snap:{90:10,100:20}},previous:null}));const lv={strikes:[100,110],perStrike:{100:{g:-20},110:{g:30}}};const before=storage.get(key);const text=sandbox.trinityDOD('SPY',lv);assert.match(text,/removed 90/);assert.match(text,/sign reversed at 100/);assert.match(text,/added 110/);assert.match(text,/spot\/greeks/);assert.equal(storage.get(key),before);sandbox.commitBaselines();assert.equal(JSON.parse(storage.get(key)).previous.date,'2026-09-28');assert.equal(sandbox.trinityDOD('SPY',lv),text);});
await test('swing cells below coloring thresholds keep values and scope totals',()=>{run("currentData=[{expiration:'2026-09-29',strike:100,dollar_gex:1234},{expiration:'2026-09-30',strike:100,dollar_gex:999999}];chainMeta={spot:100};expirationsList=['2026-09-29','2026-09-30'];swingScope='today';");node('globalMetricSelect').value='gex';sandbox.renderSwingMode();assert.match(node('voltickGridBody').innerHTML,/\$1.2K/);assert.doesNotMatch(node('voltickGridBody').innerHTML,/999|1.0M/);});
await test('chain selection race only commits newest response',async()=>{run('renderAll=()=>{};loadMarket=()=>{};');const releases={};sandbox.fetch=url=>new Promise(resolve=>{releases[url]=resolve;});node('globalSymbolInput').value='RACE_A';const a=sandbox.loadOptionsData();node('globalSymbolInput').value='RACE_B';const b=sandbox.loadOptionsData();releases['/api/data?symbol=RACE_B'](response(200,{symbol:'RACE_B',records,spot:100,fetchedAt:new Date(clock).toISOString()}));await b;releases['/api/data?symbol=RACE_A'](response(200,{symbol:'RACE_A',records,spot:90,fetchedAt:new Date(clock).toISOString()}));await a;assert.equal(run('chainMeta.symbol'),'RACE_B');assert.equal(run('chainMeta.spot'),100);});
await test('intraday race only plots newest interval',async()=>{const releases={},plots=[];sandbox.fetch=url=>new Promise(resolve=>releases[url]=resolve);sandbox.Plotly.newPlot=(...args)=>plots.push(args);node('hiroInterval').value='5m';const a=sandbox.renderHiro();node('hiroInterval').value='15m';const b=sandbox.renderHiro();const bars={t:[clock],o:[1],h:[2],l:[1],c:[2],v:[5]};releases['/api/intraday?symbol=RACE_B&interval=15m&range=1d'](response(200,bars));await b;releases['/api/intraday?symbol=RACE_B&interval=5m&range=1d'](response(200,bars));await a;assert.equal(plots.length,1);assert.match(plots[0][2].title.text,/15m/);});
await test('escaped errors and stale age are visible',()=>{sandbox.showError('<img src=x onerror=x>');assert.doesNotMatch(node('errorBanner').innerHTML,/<img/);assert.match(node('errorBanner').innerHTML,/&lt;img/);clock+=300001;sandbox.updateDataBadge();assert.match(node('dataStamp').innerText,/as of.*STALE/);assert.match(node('dataModeBadge').innerText,/STALE/);clock=F.NOW;});
await test('timeout aborts hung upstream and failures remain uncached',async()=>{const ctx=server(async(url,opts)=>{if(url.includes('yahoo'))return response(500,{});return new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(Error('aborted'))));});let abort;ctx.setTimeout=(fn,ms)=>{assert.equal(ms,15000);abort=fn;return 1;};ctx.clearTimeout=()=>{};const req=request(ctx);abort();assert.equal((await req).code,503);assert.equal(vm.runInContext('serverChainCache.size',ctx),0);});
console.log(`${count} tests passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
